Review
Lyapo4ka/karty-podskazhut pull request #1
Opened 2024-10-28 11:42 UTC by Lyapo4ka

Здравствуйте! 
Проект карты подскажут готов к ревью. 
Спасибо!

2024-10-28 13:10 UTC, Avaakum requested changes
Добрый день. У вас получилась хорошая работа!

_Что понравилось:_

- работают темы
- отличная структура файлов проекта
- Хорошие стили 
- Отзывчивая верстка


_Что необходимо исправить:_


- **Все комментарии, кроме комментариев с пометками «Можно лучше» и «Отлично». А так же не забудьте проверить, есть ли свёрнутые комментарии, которые обычно находятся по центру страницы с ревью при прокрутке вниз, и выглядят следующим образом https://disk.yandex.ru/i/FyX-8tzeqLjimw**

- https://disk.yandex.ru/i/21XLoWkeNjVKIw  Нужно указать альтернативный шрифт (тип засечек для выбора шрифта браузера без засечек по-умолчанию для основного шрифта Inter, **и для второго шрифта  "STIX Two Text" тип с засечками, serif) для каждого значения font-family в проекте, кроме файла подключения шрифтов, где это св-во задаёт только название подключаемого шрифта



- При ширине экрана 1440px _не совпадает с макетом_:
  -  https://disk.yandex.ru/i/vumBwwfaT9pyfw // https://disk.yandex.ru/i/JJ5jD0l2aXfJbQ // https://disk.yandex.ru/i/5AvYTJvWeLGFzw отступы/размеры элементов, необходимо сверить со значениями из макета(задания)

- При ширине экрана 360px _не совпадает с макетом_:
  - Аналогично есть недочёты в отображении, контролируйте с помощью PixelPerfect

-   **В проекте есть недочёты в отображении по макету, контролируйте самостоятельно с помощью PixelPerfect перед следующей итерацией:**
  - Для более точного контроля отображения вёрстки можно воспользоваться [расширением PixelPerfect](https://chrome.google.com/webstore/detail/perfectpixel-by-welldonec/dkaagdgjmgdmbnecmcefdhjekcoceebi  )  для `Chrome`, для этого в фигме выделить весь макет, экспортировать его картинкой и наложить на вёрстку в браузере. Плагин позволяет наложить изображение на вёрстку в браузере, тем самым можно с легкостью подправить недочёты по отображению. А так же, если включить в расширении инверсию цвета и прозрачность 50%, то соответствие по пикселям и цветам видно лучше, так как при сложении цветов получается однородный серый цвет.
 
    - 		https://disk.yandex.ru/i/2wqd0d3sHHV4nQ  примерно от 360px до 410px ширины экрана страница прокручивается по горизонтали
   - Для некоторых элементов нужно поменять стили. Для устранения горизонтального скролла часто применяют подобный подход: можно прямо в Dev Tools(или через IDE) по одной скрывать секции и смотреть когда он пропадает, и потом добавляют по одной устраняя скролл на всех разрешениях.  Плюс можно добавить например красный бордер(или аутлайн) для всех элементов(селектор для всех элементов со стилей `* {outline: 1px red solid; }`, можно добавить в файл стилей  ) и посмотреть что вылезает. А так же можно еще раз просмотреть уроки с платформы, где тоже есть много полезных советов. 
    - _Скролл нужно убирать без св-ва overflow, нужно подправить верстку на тех интервалах ширина экрана где это необходимо_



_Что можно улучшить:_

- Все комментарии с пометкой "Можно лучше"
- Для всех функций ` var() ` в CSS нужно задать резервные значения,  на случай если доступ к кастомному свойству по имени будет невозможен. 
- Можно использовать атрибуты `target="_blank"` для ссылок на сторонние ресурсы для того чтобы пользователю не приходилось заново открывать сайт проекта
- больше использовать currentColor, где это возможно
- больше использовать vi вместо vw


Желаю успеха!

2024-10-28 13:10 UTC, Avaakum commented on index.html
> +          <li class="header__theme-button header__theme-button_type_dark">Тёмная</li>
Интерактивные элементы это кнопки. Внутри элементов списка должны быть кнопки. И классы кнопок должны быть присвоены кнопкам.

2024-10-28 13:10 UTC, Avaakum commented on index.html
> +          <li class="header__theme-button header__theme-button_type_dark">Тёмная</li>
Потом для селектора тега кнопки с псевдо-классом  ` :disabled ` нужно задать св-во ` pointer-events: none; `, что бы даже курсор не менялся и на неактивную кнопку нельзя было нажать

2024-10-28 13:10 UTC, Avaakum commented on styles/style.css
> +  letter-spacing: 9px;
Слишком большой отступ, сверьте с макетом

2024-10-28 13:10 UTC, Avaakum commented on index.html
> +        <p class="content__paragraph">И кстати, сейчас необязательно охотиться за редкими физическими колодами Oblique Strategies — тем более, что их моментально разбирают фанаты Ино. Есть довольно с
Слово "веб-сайты" так же должно быть ссылкой из макета

2024-10-28 13:10 UTC, Avaakum commented on styles/style.css
> +.colored-text::after {
Декорация для части текста не отображается при тёмной теме. Нужно добавить паттерн  так же как для кнопки в шапке страницы.

2024-10-28 13:10 UTC, Avaakum commented on index.html
> +        <div class="header__logo">
Нужно вынести логотип из тега nav. Он не относится к навигации


---

**Можно лучше:**

Логотип должен быть ссылкой **без атрибута href,**(что бы по ссылке не было перехода). А так же, что бы при навигации с клавиатуры этот элемент не получал видимый фокус. **Пустой атрибут href тоже нужно удалить.**

2024-10-28 13:10 UTC, Avaakum commented on index.html
> +        <picture class="content__picture">
---

**Отлично:**

Отличная семантика и структура

2024-10-28 13:10 UTC, Avaakum commented on index.html
> +        <article class="content__blockquote">«Эти карты появились, потому что я оказывался в рабочих ситуациях (особенно в звукозаписывающих студиях), когда из-за паники быстро забывал, что кроме сам
Некорректная семантика, используйте для цитаты тег blockquote

Примеры и варианты значений этого тега можно посмотреть поискав по названию тега на

https://doka.guide/
https://developer.mozilla.org/ru/

2024-10-28 13:10 UTC, Avaakum commented on index.html
> +      <div class="footer__copyright">VЁRSTKA</div>
Используйте тег P или span для небольшого декоративного текста

2024-10-29 09:57 UTC, Lyapo4ka commented on styles/style.css
> +  letter-spacing: 9px;
По макету letter-spacing: 9px все верно

2024-10-29 13:35 UTC, Lyapo4ka commented
Здравствуйте! Внесла правки

2024-10-30 13:16 UTC, Avaakum commented on styles/style.css
> +  letter-spacing: 9px;
Имеется в виду, что нужно сверить при наложении скрина макета на html страницу. Если при таком значении совпадает в пределах погрешности по px, то действительно верно. Figma автоматически добавляет некоторые св-ва и в первую очередь стоит сверять визуальную составляющую на html странице в браузере.

2024-10-30 13:31 UTC, Avaakum approved these changes
Развернуть общий комментарий ⬇︎

Здравствуйте! Рад вам сообщить, что ваша работа принята. 

---

_Что необходимо исправить:_

- **Все комментарии в коде. А так же не забудьте проверить, есть ли свёрнутые комментарии, которые обычно находятся по центру страницы с ревью при прокрутке вниз, и выглядят следующим образом https://disk.yandex.ru/i/FyX-8tzeqLjimw**

- Соответствие макету:
  -  https://disk.yandex.ru/i/LMi8li92pp7fuA
  -  https://disk.yandex.ru/i/dP54An9ke8P7HA // https://disk.yandex.ru/i/YBVa00U9P7723g // https://disk.yandex.ru/i/mq55_yuiil0BjQ // https://disk.yandex.ru/i/0rRcag5pWsZgvw при мобильной ширине есть ещё много несоответствий макету

- https://disk.yandex.ru/i/JFsSex-HIuqgiQ есть горизонтальный скролл


---




Ссылки:

- Можно использовать неразрывные пробелы для того чтобы текст не переносился в неожиданных местах. Неразрывные пробелы заменяют обычные, если нужно чтобы какая-то фраза не переносилась, например не нужно чтобы "на собаках" раскидывалось по разным строчкам при некоторых ширинах экранов, тогда `«на&nbsp;собаках»`. Но если страница с адаптацией, то всегда стоит проверять как текст с пробелами выглядит на всех ширинах.
- Про альтернативный текст для картинок https://habr.com/ru/post/341810/
- [Ссылка про подгрузку шрифтов](https://only-to-top.ru/blog/tools/2019-03-13-nastrojte-pokaz-vsego-teksta-vo-vremya-zagruzki-veb-shriftov.html) 


Несколько  ссылок на материал по теме нативных CSS переменных от авторов практикума:

- [1 часть](https://tproger.ru/articles/custom-properties-in-css-part-1/)

- [2 часть](https://tproger.ru/articles/custom-properties-in-css-part-2/)

- [3 часть](https://tproger.ru/articles/custom-properties-in-css-part-3/)



**Hover и псевдоэлементы**

Псевдоэлементы:

- https://developer.mozilla.org/ru/docs/Web/CSS/Pseudo-elements
- https://habr.com/ru/post/154319/
-  https://webformyself.com/krutoe-ispolzovanie-psevdoelementov-css-before-i-after/
-  https://www.internet-technologies.ru/articles/5-priemov-css3-s-psevdoelementami-before-i-after.html

Hover:

- Базовая спека http://htmlbook.ru/css/hover		
- https://codepen.io/igosheva_nastya/pen/qeJmMM

2024-10-30 13:31 UTC, Avaakum commented on index.html
> +      <div class="footer__copyright"><p>VЁRSTKA</p></div>
**Можно лучше:** Лишний див, присвойте класс сразу для тега  p

2024-11-03 09:13 UTC, merged